# Generated by Django 4.1.1 on 2024-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_auto_20240516_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bills',
            name='rec_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
