# Generated by Django 4.1.1 on 2024-03-13 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0022_alter_saleorder_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.company_payment_term'),
        ),
    ]
