# Generated by Django 4.1.1 on 2024-03-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0023_alter_saleorder_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Save', 'Save')], default='Save', max_length=10),
        ),
    ]
