# Generated by Django 4.1.1 on 2024-03-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0024_alter_saleorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Save', 'Save')], default='Draft', max_length=10),
        ),
    ]
