# Generated by Django 4.1.1 on 2024-03-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0025_alter_saleorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer'),
        ),
    ]
